spring:
  profiles:
    active: test
    group:
      prod:
        - prod
        - secret
      dev:
        - dev
        - example
      test:
        - dev
        - test

  application:
    name: mc-archieve

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

service:
  jwt:
    expiration: 900000 # 15 minutes


--- # prod
spring:
  config:
    activate:
      on-profile: prod

--- # dev
spring:
  config:
    activate:
      on-profile: dev

