spring:
  profiles:
    active: prod
    group:
      prod:
        - prod
        - secret
      dev:
        - dev
        - example

  application:
    name: mc-archieve

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

--- # prod
spring:
  config:
    activate:
      on-profile: prod

--- # dev
spring:
  config:
    activate:
      on-profile: dev

