name: Build Docker image and deploy

on:
  push:
    branches:
      - t1-deploy-error-check

jobs:
  docker-login-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Print environment variables
        run: |
          echo "DOCKER_HUB_USERNAME=${DOCKERHUB_USERNAME}"
          echo "DOCKER_HUB_TOKEN=${DOCKERHUB_TOKEN}"
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME_TEST }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN_TEST }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

